services:
  backend:
    image: node:18-alpine
    container_name: SnippetBox2-backend-dev
    working_dir: /app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - node_modules_backend:/app/node_modules
      - ./data:/app/data
    environment:
      - NODE_ENV=development
      - JWT_SECRET=development_secret_change_in_production
      - JWT_EXPIRES_IN=15m
    command: sh -c "rm -f /app/data/db.sqlite3 && npm install && npm install -g nodemon ts-node && npm run dev:server"
    networks:
      - SnippetBox2-network

  frontend:
    image: node:18-alpine
    container_name: SnippetBox2-frontend-dev
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    environment:
      - REACT_APP_API_URL=http://backend:5000/api
      - CHOKIDAR_USEPOLLING=true
      - npm_config_unsafe_perm=true
      - ESLINT_NO_CACHE=true
    command: sh -c "npm install --cache=/tmp/.npm && ESLINT_NO_CACHE=true npm start"
    networks:
      - SnippetBox2-network
    depends_on:
      - backend

networks:
  SnippetBox2-network:
    driver: bridge

volumes:
  node_modules_backend: 