version: '3.8'

services:
  backend:
    image: node:16-alpine
    container_name: snipprompt-backend-dev
    working_dir: /app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - node_modules_backend:/app/node_modules
      - ./data:/app/data
    environment:
      - NODE_ENV=development
      - JWT_SECRET=${JWT_SECRET:-development_secret_change_in_production}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-15m}
    command: sh -c "npm install && npm install -g nodemon ts-node && npm run dev:server"
    networks:
      - snipprompt-network

  frontend:
    image: node:16-alpine
    container_name: snipprompt-frontend-dev
    working_dir: /app
    user: "1000:1000"
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - node_modules_frontend:/app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm start"
    networks:
      - snipprompt-network
    depends_on:
      - backend

networks:
  snipprompt-network:
    driver: bridge

volumes:
  node_modules_backend:
  node_modules_frontend: 