services:
  snippetbox2:
    image: danielgap/snippetbox2:latest
    container_name: SnippetBox2
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped
